name: gps_connectivity
description: A Flutter plugin that checks whether GPS is ON or OFF, it can listen for GPS change.
version: 0.0.4
homepage:
repository: https://github.com/khamidjon/gps_connectivity

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">= 1.22.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  test: ^1.16.4
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: uz.thunder.gps_connectivity
        pluginClass: GpsConnectivityPlugin


